language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: "JSON schema validation on workflow.json"
      before_script:
        - npm install shelljs
        - npm install ajv@7.0.3
      script:
        - node $TRAVIS_BUILD_DIR/scripts/schema_validate.js
    - stage: "File validation rules"
      script:
        - $TRAVIS_BUILD_DIR/scripts/travis_release.sh
    - stage: "Validate the data inside the details object in each workflow.json file"
      script:
        - node $TRAVIS_BUILD_DIR/scripts/json-details-scripts/details_validator.js
