version: 2.1

orbs:
  node: circleci/node@5.0.3
  general-platform-helpers: okta/general-platform-helpers@1.5

workflows:
  validation:
    jobs:
      - node/test:
          name: Jest tests
          test-results-for: jest
          test-results-path: jest-junit.xml
          run-command: test:ci
      - node/run:
          name: JSON schema validation on workflow.json
          npm-run: validate:schema
      - node/run:
          name: File validation rules
          npm-run: validate:release
      - node/run:
          name: Validate the data inside the details object in each workflow.json file
          npm-run: validate:details
  semgrep:
    jobs:
      - general-platform-helpers/job-semgrep-prepare:
          name: semgrep-prepare
      - general-platform-helpers/job-semgrep-scan:
          name: "Scan with Semgrep"
          requires:
            - semgrep-prepare
